# Generated by Django 3.2.5 on 2023-04-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='path',
            field=models.CharField(default=1, max_length=255, verbose_name='Path'),
            preserve_default=False,
        ),
    ]
