# Generated by Django 3.2.5 on 2023-04-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_version_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='tag',
            field=models.CharField(default='', max_length=100, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='version',
            name='overview',
            field=models.TextField(blank=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.version')),
            ],
        ),
    ]
